commit branch form control
mriiad/warid-initiative pull request #8
Opened 2023-07-19 21:06 UTC by HajarBouhamida

2023-07-22 20:36 UTC, mriiad requested changes

2023-07-22 20:36 UTC, mriiad commented on extranet/src/SignupForm.tsx
> +            <Button type="submit" color="primary" style={{ color: 'white' }} className={classes.button}>
avoid inline style, you can add the property color: white to the class button in the the makestyles above

2023-07-22 20:36 UTC, mriiad commented on extranet/src/SignupForm.tsx
>    const classes = useStyles();
use destructuring assignment solution

2023-07-22 20:36 UTC, mriiad commented on extranet/src/SignupForm.tsx
>    const classes = useStyles();
```suggestion
  const { container, imageContainer, image, formContainer, bar, button } = useStyles();
```

This will allow you to use the style easily and in a proper way

2023-07-22 20:36 UTC, mriiad commented on extranet/src/SignupForm.tsx
>      <div className={classes.formContainer}>
an example based on the code suggestion above
```suggestion
    <div className={formContainer}>
```
same for the rest of code

2023-07-29 17:30 UTC, HajarBouhamida commented on extranet/src/SignupForm.tsx
>      <div className={classes.formContainer}>
it's done

2023-07-29 17:30 UTC, HajarBouhamida commented on extranet/src/SignupForm.tsx
>    const classes = useStyles();
it's done

2023-08-05 03:56 UTC, mriiad commented
@HajarBouhamida In the latest commit, I've integrated the styled-components library to manage containers within the whole project.
The idea is to create all the custom containers (simple JSX combined with styles) using this library.
As we move forward, the remaining styling aspects will consistently be furnished using the makeStyles from MUI.
This strategy should combine both styed-components & makeStyles to have something like parent (containers) and children (the rest of components/jsx).

2023-08-08 23:13 UTC, merged